//Given two strings s and t which consist of only lowercase letters.

//String t is generated by random shuffling string s and then add one more letter at a random position.

//Find the letter that was added in t.

#include <iostream>
#include <vector>
#include <unordered_map>
using namespace std;

class Solution {
public:
    char findTheDifference(string s, string t) {
        unordered_map<char,int> elements;
        for(int i=0;i<s.length();i++){
            elements[s[i]]++;
        }
        for(int i=0;i<t.length();i++){
            if(elements[t[i]]--==0)
                return t[i];
        }
        return ' ';
    }
};

int main(){}
